# Generated by Django 3.0.7 on 2020-06-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200618_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endtime',
            field=models.PositiveIntegerField(),
        ),
    ]
