# Generated by Django 3.0.7 on 2020-06-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200618_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('OnProgress', 'OnProgress'), ('Done', 'Done')], default='OnProgress', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Middle'), ('L', 'Large')], max_length=10),
        ),
    ]
