# Generated by Django 3.0.7 on 2020-06-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200619_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tasktype',
            field=models.CharField(choices=[('Small', 'Small'), ('Middle', 'Middle'), ('Large', 'Large')], max_length=10),
        ),
    ]
