# Generated by Django 3.0.7 on 2020-07-09 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200708_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='spenttime',
        ),
        migrations.AddField(
            model_name='task',
            name='spenthour',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='task',
            name='spentmin',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
    ]
