# Generated by Django 3.0.7 on 2020-07-09 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200708_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='endtime',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(19)]),
        ),
        migrations.AlterField(
            model_name='activity',
            name='starttime',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(18)]),
        ),
    ]
