# Generated by Django 3.0.7 on 2020-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_task_donedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ontime_late',
            field=models.CharField(default='Ontime', max_length=100),
        ),
    ]
